kkoomen/vim-doge

- ftplugin/python.vim
- test/filetypes/python/functions.vader
By contributing to DoGe you agree to the following statements **(Put an `x` inside every [ ] you agree with)**:
According to the following link: https://docs.python-guide.org/writing/documentation/ there should be two sections with the numpy style guide. The first should be a summary
line, and then there should be a more detailed, extended description of
the function. This PR will add this extra TODO item for an extended
description.
> Added a line for extended description for numpy style

- autoload/doge/generate.vim
- autoload/doge/helpers.vim
The plugin does not work when vim locale is not en; i.e. for python files it raises an error on `<C-D>`:
```
Wykryto błąd podczas przetwarzania function doge#generate[3]..doge#generate#pattern:
wiersz   33:
E117: Nieznana funkcja: doge#preprocessors#python#tokens
Wykryto błąd podczas przetwarzania function doge#generate:
wiersz    3:
E171: Brak :endif 
```
When calling not-existing functions, vim generates localized errors messages that do not match
catch statements in the plugin.
This patch replaces the current catching method for `E117` and `E486` by one method from `:h catch`: `catch /^Vim\%((\a\+)\)\=:<error number>/`
> Fix catch "Pattern not found"/"Unknown function" when locale is not en

- README.md
- ftplugin/python.vim
- test/filetypes/python/functions-doc-sphinx.vader
Following issue #21, this PR changes `reST` documentation format to support `Sphinx` format.
I can move all of this to a new documentation format if needed.
By contributing to DoGe you agree to the following statements:
> Add support for Sphinx format

- README.md
- autoload/doge/generate.vim
- autoload/doge/helpers.vim
- doc/doge.txt
- doc/tags
- plugin/doge.vim
This just adds a command – `:DogeGenerate` – to generate documentation.
_**Note:** The `vimdoc` command did not add anything to the help file, so I took the initiative to add a section manually. I can remove it if necessary._
> Add the `:DogeGenerate` command to generate documentation

- README.md
- doc/doge.txt
- doc/tags
- ftplugin/python.vim
- plugin/doge.vim
This adds a new configurable setting – `g:doge_enable_mappings` – to enable or disable mappings.
Its value is set to `1` by default, so all mappings will be added (as is the case right now).
If set to `0`, then no mappings will be added, but the "plugin" mappings (ie: `<Plug>(doge-generate)`) will still be declared.
> Add a configurable setting to enable or disable mappings

- autoload/doge.vim
- autoload/doge/comment.vim
- doc/doge.txt
- doc/tags
- plugin/doge.vim
- test/options/doge_buffer_mappings.vader
- test/options/doge_comment_interactive.vader
New option to use buffer mappings instead of normal mappings.
Buffer mappings are enabled when DoGe is successfully started, and
unmapped when finished.
Same stuff of the PR #43, but cleaned up. The wrap-around feature has been moved to a different PR, since it's a different thing.
Reasons for the PR:
- so that you don't need to reserve a key like `<tab>` for DoGe, that is used sporadically and can use buffer mappings as other snippet plugins do
- fixes #16 and related issues
> g:doge_buffer_mappings (default 0)

- README.md
- autoload/doge.vim
- doc/doge.txt
- doc/tags
- plugin/doge.vim
Defines the modes in which doge jump mapping should work.
Default: ['n', 'i', 's']
For those that use Tab for autocompletion/snippet expansion, so that it's still possible to use it that way in a doge block. For me normal mode and select mode are enough.
> g:doge_comment_jump_modes

- autoload/doge/comment.vim
- autoload/doge/generate.vim
- doc/doge.txt
- doc/tags
- plugin/doge.vim
Check on InsertLeave if there are placeholders left, if not, deactivate
doge.
Before this PR, after the last placeholder was consumed, the first Tab keypress would still use doge mapping, which is undesiderable. It checks on InsertLeave, so that if the placeholder is reached, but not consumed, doge remains active.
> Deactivate doge if no placeholders left

- README.md
This is a small update to the readme to include a required python package which is needed for c/c++. It also adds an example of how to set the `LD_LIBRARY_PATH` variable.
> Add required prereq for c/c++

- autoload/doge/pattern.vim
- autoload/doge/token.vim
- ftplugin/ruby.vim
- playground/test.rb
- test/filetypes/ruby/functions.vader
Fix ruby function without parentheses
And I let `parameters.match` support the use of arrays because using one regular expression can't satisfy my needs.
And I let `l:curr_line_raw` contains the `\n` because ruby needs to determine if there is a `\n`.
https://github.com/weirongxu/vim-doge/blob/4c43cd41cf5b099b93225a3e2616f2544d639a6e/autoload/doge/pattern.vim#L29
> fix(ruby): Fix ruby keyword arguments and without parentheses

- ftplugin/sh.vim
- playground/test.sh
- test/filetypes/sh/functions.vader
If you don't mind, let me add an Output section to the documents of file type sh.
Google's styleguide has an Output section.
Currently, vim-doge does not have an Output section.
Merging this Pull Request will add the Output section.
> feat: Added the Outputs part to type sh

- autoload/doge/pattern.vim
- test/commands/create-doc-standard.vader
By contributing to DoGe you agree to the following statements
Accidently closed the previous one #104. This is the replacement.
<hr />
This handles the special case, when .vim runtimepaths are lying around
on the system, but are not added in the runtimepath of the running
(neo)vim instances itself.
I had a `~/.vim` folder lying around in my system. 
Executing `:DogeCreateDocStandard ...` opened `~/.vim/after/ftplugin/...`, 
I use neovim and the `~/.vim` folder is no longer included in my runtimepath setup,
so I added this check.
> fix(pattern): create custom doc only in valid rtp's

- CONTRIBUTING.md
By contributing to DoGe you agree to the following statements:
Just to avoid the confusion of having the curly brackets there :slightly_smiling_face:
> docs(contributing): use square brackets for template property

- autoload/doge/preprocessors/javascript.vim
- src/parsers/typescript.service.ts
- test/filetypes/javascript/es6.vader
- test/filetypes/javascript/functions-inside-objects.vader
- test/filetypes/javascript/functions.vader
- test/filetypes/typescript/class-methods.vader
- test/filetypes/typescript/generics.vader
- test/filetypes/typescript/return-types.vader
Fixes #312 
This PR fixes:
- looks for `return_statement` syntax nodes within the body and adds the `@return` as well if there's no type specific, but a `return_statement` node has been found with neither one of the values: `void(0)`, `void 0` and `undefined`
- some incorrect return types for promise functions
> Dynamic JS/TS return types

- plugin/doge.vim
By contributing to DoGe you agree to the following statements:
When upgrading pluging, the `plugin/doge.vim` will be executed twice (one for initial load of vim-doge, one for loading upgraded vim-doge). Using `:command` to redefine will cause vimscript error, which can be easily avoided by using `:command!`.
> fix: avoid redefine command error

- autoload/doge/pattern.vim
- test/options/doge_doxygen_settings.vader
> Only replace \t chars when not followed by "param"

- autoload/doge.vim
Thank you for helping out vim-doge!
By contributing to vim-doge you agree to the following statements:
[This](https://github.com/kkoomen/vim-doge/issues/588) was also an issue for me.
Adding `/bin/vim-doge-helper.exe` to `let l:executables` in the function `doge#run_parser()` resolved the issue.
> Now runs in Windows

- autoload/doge.vim
- test/undo-cursor-pos.vader
Using `%!tree` will jump the cursor to the top of the file, thus when generated a comment and then pressing `u`, it will jump the cursor back to the top of the file. Using `writefile()` solves the problem.
Fixes #309
> Fix undo cursor position bug

- helper/Cargo.lock
- helper/src/cpp/parser.rs
- test/filetypes/cpp/functions.vader
> fix(cpp): resolve default param case

- .github/workflows/tests.yml
- helper/src/rust/parser.rs
- test/filetypes/rust/functions.vader
> fix(rust): handle destructured params case (#617)

- autoload/doge.vim
Additional PR for the case as described in #621 where the user might have disabled `filetype plugin on`. In that case, the `ftplugin/<filetype>.vim` variables won't exist. We could've picked any of the default variables that are always defined in the `ftplugin/<filetype>.vim` folder, so I simply took `b:doge_supported_doc_standards`. If this doesn't exists when `doge#generate` is executing, then we'll print an error message suggesting that it might be that the user did not set `filetype plugin on` in their `.vimrc`.
> handle case when ftplugin is disabled

- autoload/doge.vim
- helper/src/php/parser.rs
- test/filetypes/php/functions-with-namespaces.vader
Fixes #621, where as the PHP parser only included use statement usages in the form of `use Foo\Bar;` but not `use Foo;`.
> PHP single name use statement case

- .github/workflows/tests.yml
- autoload/doge.vim
- helper/src/typescript/docs/jsdoc.yaml
- helper/src/typescript/parser.rs
- test/filetypes/typescript/class-properties.vader
> Add support for class prop documentation

- helper/src/typescript/parser.rs
- test/filetypes/javascript/functions.vader
> Ignore member expressions as function param in JS/TS

- helper/src/python/docs/doxygen.yaml
- helper/src/python/docs/google.yaml
- helper/src/python/docs/numpy.yaml
- helper/src/python/docs/reST.yaml
- helper/src/python/docs/sphinx.yaml
- helper/src/python/parser.rs
- test/filetypes/python/classes-doc-doxygen.vader
- test/filetypes/python/classes-doc-google.vader
- test/filetypes/python/classes-doc-numpy.vader
- test/filetypes/python/classes-doc-sphinx.vader
- test/filetypes/python/classes.vader
> Implement class docstrings
